---
- name: Prepare system to install Docker
  block:
    - name: Transfer and run bash script
      script:
        cmd: docker_prepare.sh

    - name: Update repo cache
      apt:
        update_cache: yes

- name: Install Docker to Debian server
  apt:
    name: "{{ docker_packages }}"
    state: latest

- name: Add "{{ ansible_user }}" to group docker
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Create a network
  docker_network:
    name: "{{ docker_network_name }}"
...
