---
- name: Start NGINX service
  service:
    name: nginx
    state: started
    enabled: true

- name: Soft reload NGINX
  shell: 'nginx -s reload'

- name: Restart NGINX
  service:
    name: nginx
    state: restarted
