---
- name: Pull nginx image
  docker_image:
    name: nginx
    source: pull
    tag: latest

- name: Create volume directory for nginx data
  file:
    path:
      /opt/nginx/data
    state: directory
    owner: root
    group: docker
    mode: 0755
    recurse: true

- name: Create volume directory for nginx config
  file:
    path:
      /opt/nginx/config
    state: directory
    owner: root
    group: docker
    mode: 0755
    recurse: true

- name: Place php page to /opt/nginx/data
  copy:
    src: index.php
    dest: /opt/nginx/data/index.php
    owner: root
    group: docker
    mode: 0664

- name: Place nginx config to /opt/nginx/config
  copy:
    src: default
    dest: /opt/nginx/config/default
    owner: root
    group: docker
    mode: 0664 

- name: Start nginx container
  docker_container:
    name: nginx
    image: nginx
    networks:
      - name: "{{ docker_network_name }}"
    ports:
      - "80:80"
    volumes:
      - /opt/nginx/data:/usr/share/nginx/html
      - /opt/nginx/config/default:/etc/nginx/conf.d/default.conf
    restart_policy: always

...
