---
- name: Install essentials packages
  become: 'yes'
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
    install_recommends: no
      
- name: adding existing user "{{ ansible_user }}" to group www-data
  user:
    name: "{{ ansible_user }}"
    groups: www-data
    append: yes
  become: yes

- name: Add user in sudoers file
  become: 'yes'
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%{{ user }}'
    line: '%{{ user }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Set authorized key took from file
  become: 'yes'
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', ssh_keys) }}"
...
